data = read.delim("clipboard")
summary(iris)
head(iris)
by(iris$Petal.Length,iris$Species, summary)
mean(iris$Sepal.Length)
var(iris$Sepal.Length)
boxplot(iris$Petal.Length)
boxplot(Petal.Lenght~Species,data=iris,main='Petal Lenght',xlab="Species",ylab="Lenght")
hist(iris$Petal.Length)
hist(iris$Sepal.Width)
hist(iris$Sepal.Width[iris$Species=="setosa"])
hist(iris$Sepal.Width[iris$Species=="versicolor"])
d=density(iris$Petal.Length)
plot(d)
d=density(iris$Sepal.Width[iris$Species=="versicolor"])
plot (d)
install.packages("ggplot2")
library(ggplot2)
data_yuda=read.csv("C:/Users/Yuda Hp/Downloads/Dataset/DirectMarketing.csv")
qplot(data_yuda$AmountSpent, data_yuda$Salary)
plot(data_yuda$AmountSpent, data_yuda$Salary)
